on:
  workflow_call:

jobs:
  test-job:
    runs-on: macos-13
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Flutter"
        run: |
          brew install flutter
      - name: "Flutter macOS build"
        run: |
          flutter build macos