on:
  workflow_call:

jobs:
  build-snap-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run Snapcraft"
        uses: snapcore/action-build@v1