on:
  workflow_call:

jobs:
  build-snap-job:
    name: Build Linux-compatible Snap package
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Flutter"
        run: |
          sudo snap install flutter --classic
      - name: "Run Snapcraft"
        uses: snapcore/action-build@v1
        with:
          path: builders/