name: Build Snap
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        run: |
          snap install flutter --classic
      - name: Run snapcraft
        uses: snapcore/action-build@v1
