on:
  workflow_call:

jobs:
  build-aab-job:
    name: Build Android App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        run: |
          sudo snap install flutter --classic
      - name: Flutter AAB
        run: |
          flutter build appbundle