name: Build Android App Bundle
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        run: |
          sudo snap install flutter --classic
      - name: Flutter AAB
        run: |
          flutter build appbundle
