name: "PR Merge"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  analyze:
    uses: ./.github/workflows/analyze.yaml
  test:
    needs:
      - analyze
    uses: ./.github/workflows/test.yaml
  build-snap:
    needs:
      - test
    uses: ./.github/workflows/build-snap.yaml
  build-aab:
    needs:
      - test
    uses: ./.github/workflows/build-aab.yaml
  build-macos:
    needs:
      - test
    uses: ./.github/workflows/build-macos.yaml
