on:
  workflow_call:
    inputs:
      snap-path:
        required: true
        type: string
      release:
        required: true
        type: string
    secrets:
      snapcraft-store-credentials:
        required: true

jobs:
  publish-snap:
    runs-on: ubuntu-latest
    steps:
      - name: "Download snap artifact"
        uses: actions/download-artifact@v3
        with:
          name: snap-artifact
      - name: "Run Snapcraft"
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft-store-credentials }}
        with:
          snap: ${{ inputs.snap-path }}
          release: ${{ inputs.release }}