on:
  workflow_call:

jobs:
  test-job:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.8
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run tests"
        run: |
          flutter test